b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Areas/admin/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeDeneme1.Areas.admin.Controllers
{
    public class MainController : Controller
    {
        // GET: admin/Home
        public ActionResult AdminGiris()
        {
            return View();
        }

        public ActionResult CalisanGiris()
        {
            return View();
        }
    }
}

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Areas/admin/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeDeneme1.Areas.admin.Controllers
{
    public class SharedController : Controller
    {
        // GET: admin/Shared
        public ActionResult _Layout()
        {
            return View();
        }
    }
}

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeDeneme1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdminEkrani()
        {
            

            return View();
        }
        public ActionResult CalisanDuzenle()
        {
            return View();
        } 
        public ActionResult Duzenle()
        {
            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Areas/admin/Views/Main/AdminGiris.cshtml
@{
    //ViewBag.Title = "Admin sayfasıdır";
    Layout = "~/Areas/admin/Views/Shared/Layout.cshtml";
}


<html>
<head>
   
</head>
<body>
   


    <div class="container">
        <div class="row">
            <div class="col-lg-4">
               
            </div>
            <div class="col-lg-4">
                    <form class="form-signin">
                        <h2 class="form-signin-heading">Lütfen Giriş Yapın</h2>
                        <label for="inputEmail" class="sr-only">Email adres :</label>
                        <input type="email" id="inputEmail" class="form-control" placeholder="Email adres" required autofocus>
                        <label for="inputPassword" class="sr-only">Şifre :</label>
                        <input type="password" id="inputPassword" class="form-control" placeholder="Şifre" required>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" value="remember-me"> Beni Hatırla
                            </label>
                        </div>
                                 <button class="btn btn-lg btn-primary" href="#" type="submit">Giriş Yap &raquo;</button>
                      
                   </form>

                </div>
               
            </div>
           
        </div>

      
</body>
</html>

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Areas/admin/Views/Main/CalisanGiris.cshtml
@{
    ViewBag.Title = "CalisanGiris";
    Layout = "~/Areas/admin/Views/Shared/Layout.cshtml";
}

<html>
<head>
 
</head>
<body>
   
        <div class="row">
            <div class="col-lg-2">

            </div>

                <div class="col-lg-6">
                    <div class="jumbotron">
                        <h5>---Hoşgeldiniz.Lütfen aşağıdaki bilgileri eksiksiz doldurun...</h5>
                       
                    </div>

                </div>
          </div>
 
    
    <div class="container">
        <div class="row">
            <div class="col-lg-2">

            </div>
            <div class="col-lg-2">
                <label for="ad" class="text-primary">Ad :    </label>
                <input type="text" id="ad" class="text-primary" placeholder="Ad" required autofocus>
                <br/>
                <br /><label for="soyad" class="text-primary">Soyad :</label>
                <input type="text" id="soyad" class="text-primary" placeholder="Soyad" required autofocus>
                <br />
                <br /><label for="unvan" class="text-primary">Ünvan :</label>
                <select class="form-control text-primary">  <option> Yazılım Uzmanı </option> </select>
                <br />
                <label for="KullaniciAd" class="text-primary">Kullanıcı Adınız :    </label>
                <input type="text" id="KullaniciAd" class="text-primary" placeholder="Kullanıcı Ad" required autofocus>
                <br /><br />
                <label for="sifre" class="text-primary">Şifre :</label>
                <input type="password" id="sifre" class="text-primary" placeholder="Şifre" required>
                <br /><br />
                <label for="sifreTekrar" class="text-primary">Şifre Tekrar:</label>
                <input type="password" id="sifreTekrar" class="text-primary" placeholder="Şifre Tekrar" required>
                <br/><br/>
                <div />
                 <div class="col-lg-5">

                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-3">
            </div>
            <div class="col-lg-1">
                <button type="button" class="btn btn-primary">Kaydol</button>
                <br /><br /><br /><br /><br /><br />
            </div>
        </div>
    </div>


</body>
</html>

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Areas/admin/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<meta name="viewport" content="width=device-width" />
@*<title>@ViewBag.Title</title>*@
<html>

<head>
    <title>
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>


    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


   



           <div class="jumbotron" style="background:#CCFFFF">
                <div class="row">
                    <div class="col-lg-1">

                    </div>

                    <div class="col-lg-10">

                        @*<div class="jumbotron" style="background:#15d4f5;color:#fff;">*@
                        <h1>Performans Değerlendirme Sistemi</h1>
                    </div>
                </div>


            </div>
            @RenderBody()


</body>
</html>

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Views/Home/AdminEkrani.cshtml
@{
    ViewBag.Title = "AdminEkrani";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    
    @*<meta name="viewport" content="width=device-width" />*@
    <title></title>

</head>
<body>

   


    <div class="col-lg-7">
        <table class="table table-striped">
            <tr>
                <td class="info">Çalışan Ad</td>
                <td class="warning">Çalışan Soyad</td>
                <td class="success">Ünvan</td>
                <td class="danger">Yapılan İş</td>
                <td class="info">Puan</td>
                <td class="warning">Açıklama</td>

            </tr>
            <tr>
                <td>Meltem</td>
                <td>Uzavcı</td>
                <td>Yazılım Uzmanı</td>
                <td>133</td>
                <td>2</td>
                <td>Daha sıkı çalışmalısın</td>

            </tr>
            <tr>
                <td>Ali</td>
                <td>Veli</td>
                <td>Test Uzmanı</td>
                <td>143</td>
                <td>5</td>
                <td>Çok iyi</td>
            </tr>
        </table>
    </div>

</body>
</html>

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Views/Home/CalisanDuzenle.cshtml
@{
    ViewBag.Title = "CalisanDuzenle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<html>
<head>

</head>
<body>

    <div class="col-lg-7">
        <table class="table table-striped">
            <tr>
                <td class="danger">Çalışan Ad</td>
                <td class="warning">Çalışan Soyad</td>
                <td class="success">Ünvan</td>
                <td class="active">Çalışan Düzenle</td>
            
            </tr>
            <tr>
                <td>Meltem</td>
                <td>Uzavcı</td>
                <td>Yazılım Uzmanı</td>
                <td><a href="Home/Duzenle"class="btn btn-warning">Düzenle </a> </td>
              
               
            </tr>
            <tr>
                <td>Ali</td>
                <td>Veli</td>
                <td>Test Uzmanı</td>
                <td><button href="Home/Duzenle" type="button" class="btn btn-warning">Düzenle</button> </td>

            </tr>
        </table>
    </div>


</body>
</html>

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Views/Home/Duzenle.cshtml
@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>

</head>
<body>
    <div class="col-lg-1">
        </div>
  
        <div class="col-lg-3">
            <div class="table-bordered">

                <div class="jumbotron" style="background:#FFFFFF">

                    <input type="text" class="form-control" placeholder="Çalışan Adı">
                    <br />
                    <input type="text" class="form-control" placeholder="Çalışan Soyadı">
                    <br />
                    <input type="text" class="form-control" placeholder="Çalışan Ünvan" />
                    <div class="col-lg-3">
                       </div>
                        <div class="col-lg-1">
                            <button type="button" class="btn btn-info"> Düzenle </button>
                        </div>

                    </div>
            </div>
    
</div>
       
</body>
</html>

@*<form class="navbar-form navbar-right">*@

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Melteeeeeeeeeeem";
}
<html>
<head>

</head>
<body>


    <div class="jumbotron" style="background:#CCFFFF">
        <div class="row">
            <div class="col-lg-1">

            </div>
            <div class="col-lg-10">

                <h2>Performans Değerlendirme Sistemi</h2>
                <p class="lead"> Performans değerlendirme sistemi çalışanlarınızı daha adil ve kolay puanlayabilmenizi, yapılacak işleri ve tamamlanmış işleri daha net görmenizi sağlar.</p>
                <br />
                @*<a class="btn btn-lg btn-primary" href="admin/Main" role="button">Üye Girişi &raquo;</a>
                <a class="btn btn-lg btn-default" href="admin/Main/CalisanGiris" role="button">Üye Ol &raquo;</a>*@
            </div>

            <div class="col-lg-1">

            </div>
        </div>
    </div>
 
            @*<button type="button" class="btn btn-outline-success">Success</button>*@
            @*@Html.ActionLink("Üye Girişi", "Index", "Main", new { area = "admin" }, new { })*@



</body>
</html>

b141200015 - Kopya/ProjeDeneme1/ProjeDeneme1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title - My ASP.NET Application</title>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <title>
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


</head>
<body>
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



    <div class="container">


        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Performans Değerlendirme Sistemi</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Ana Sayfa</a></li>
                        <li><a href="#">İletişim</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="admin/Main/AdminGiris">Üye Girişi</a></li>
                        <li><a href="admin/Main/CalisanGiris">Üye Ol</a></li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
    <div class="jumbotron" style="background:#CCFFFF">
        </div>

    <div class="col-lg-1">
    </div>
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
        <div class="list-group">
            <a class="list-group-item active">Menü</a>
            <a href="Home/CalisanDuzenle" class="list-group-item ">Çalışan Düzenle</a>
            <a href="#" class="list-group-item">Çalışan Sil</a>
            <a href="#" class="list-group-item ">İş Ekle</a>
            <a href="#" class="list-group-item">İş Güncelle</a>
            <a href="#" class="list-group-item">Puan Ekle</a>
            <a href="#" class="list-group-item">Açıklama Ekle</a>
            <a href="#" class="list-group-item">Tarih Sorgulama</a>

        </div>
    </div>
        

        @RenderBody()



        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")

        @RenderSection("scripts", required: false)

</body>
</html>